### ISSUE TITLE
problem with start

### ISSUE THREAD

**Issue by shanow7** [twelvesec/gasmask#52]
![image](https://user-images.githubusercontent.com/37192410/93015179-a4261180-f5b7-11ea-93e8-1659da816633.png)

**Comment by ZekePolarisBSH** [comment]
Well, the instructions says to use python not python3......

**Comment by ghost** [comment]
use censys==1.1.1 in requirement.txt which fixes the issue

**Comment by maldevel** [comment]
`sudo pip3 install "censys==2.0.7; python_version > '3.8'" "censys==0.0.8; python_version <= '3.8'"`
